### ISSUE TITLE
Exception in certain situations while trying to export: context is incorrect

### ISSUE THREAD

**Issue by Brachi** [Brachi/albam#38]
### Game
Resident Evil 5
### Example game file names
Any

### Blender version
2.76

### Albam version
develop at commit 913b03e7ed (probably reproducible in 0.1) 

### Observed behavior
Exception thrown when trying to export a model
```
Traceback (most recent call last):
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/blender.py", line 188, in execute
    bpy.ops.object.mode_set(mode='OBJECT')
  File "/opt/blender-2.76b/2.76/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1
```

### Expected behavior
No exceptions, of course.

### Steps to reproduce
1. Open a model ready to export
2. Delete part a mesh of that model
3. Click on export

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
