### ISSUE TITLE
Exporting: errors with meshes with no faces

### ISSUE THREAD

**Issue by Brachi** [Brachi/albam#46]
### Game
Resident Evil 5, <Custom mod>

Errors when trying to export meshes:
1. No vertices -> exception
2. Vertices, but no faces -> exception
3. Some vertices with no faces -> artifacts 

Vertices by itself use 'degenerate' triangles (e.g. invisible, see pl00ChrisNormal.arc, in mesh 0). However, it might be also a good idea to just skip exporting those kind of meshes.
For 3, it seems that the algorithm for converting triangle lists to triangle strips expects all vertices to be referenced by an index.

For 1, 2, the exception is:
```
Traceback (most recent call last):
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/blender.py", line 189, in execute
    func(obj, self.filepath)
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/engines/mtframework/blender_export.py", line 78, in export_arc
    exported_mod = export_mod156(child)
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/engines/mtframework/blender_export.py", line 168, in export_mod156
    exported_meshes = _export_meshes(blender_meshes, bounding_box, bone_palettes, exported_materials)
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/engines/mtframework/blender_export.py", line 424, in _export_meshes
    vertices_array = _export_vertices(blender_mesh_ob, bounding_box, mesh_index, bone_palette)
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/engines/mtframework/blender_export.py", line 306, in _export_vertices
    tangents = _get_tangents_per_vertex(blender_mesh)
  File "/home/sysop/.config/blender/2.76/scripts/addons/albam/engines/mtframework/blender_export.py", line 292, in _get_tangents_per_vertex
    blender_mesh.calc_tangents(uv_name)
RuntimeError: Error: Tangent space computation needs an UVMap, "UVMap" not found, aborting
```

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
